[package]

name = "zip"
version = "0.4.2"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]
license = "MIT"
repository = "https://github.com/mvdnes/zip-rs.git"
documentation = "http://mvdnes.github.io/rust-docs/zip-rs/zip/index.html"
keywords = ["zip", "archive"]
description = """
Library to support the reading and writing of zip files.
"""

[dependencies]
chrono = { version = "0.4", optional = true }
flate2 = { version = "1.0", default-features = false, optional = true }
time = { version = "0.1", optional = true }
podio = "0.1"
msdos_time = { version = "0.1", optional = true }
bzip2 = { version = "0.3", optional = true }

[dev-dependencies]
walkdir = "1.0"

[features]
deflate = ["flate2", "flate2/rust_backend"]
deflate-miniz = ["flate2", "flate2/miniz-sys"]
deflate-zlib = ["flate2", "flate2/zlib"]
default = ["bzip2", "deflate", "time", "msdos_time"]
